### ISSUE TITLE
Layers are not set up.

### ISSUE THREAD

**Issue by arp2600** [sebas77/Svelto.ECS.Examples.Survival#1]
Hi there. It took me a while to get your example working properly. Because you didn't supply a full unity project, none of the layers are set up correctly, so turning and shooting doesn't work correctly.

**Comment by sebas77** [comment]
thank you very much to point this out, I will check and fix asap!

**Comment by sebas77** [comment]
the project settings folder is now included, can you please check if it works? Any feedback overall?

**Comment by Darelbi** [comment]
It worked correctly when I tried it on July. So after the layer change
