### ISSUE TITLE
TURBO_EXAMPLE

### ISSUE THREAD

**Issue by eliasts** [sebas77/Svelto.ECS.Examples.Survival#3]
Hi.

When I enable the TURBO_EXAMPLE preprocessor directive I get a "The name `_nodes' does not exist in the current context" in the BoidsEngine.cs

**Comment by sebas77** [comment]
Hello thanks for reporting it, I think I noticed and fixed it. However you cannot use TURBO_EXAMPLE alone, it must be used together with FOURTH_TIER_EXAMPLE. Sorry for the awful defines :)

**Comment by eliasts** [comment]
Thanks for the heads up. I didn't notice this.
